### ISSUE TITLE
get_all_stock_item_list() 결과 첫번째 종목 누락 건

### ISSUE THREAD

**Issue by j4nus909** [wansanp/mquant_study#4]
일하다가 문득... 떠올라서 올립니다. 
제가 어제 보내드린 PR때문에 발생하는 이슈가 있습니다. 

get_all_stock_item_list() 의 결과에서 맨첫번째 종목이 누락됩니다. 
마지막 컬럼을 가져오기 위해서 loop 전에 54라인에서 미리 한번 file.readline()을 했기 때문인데 
아래 주소의 69라인에서 제목행을 제거하기 위해 한번 더 한행을 날립니다. 

https://github.com/wansanp/mquant_study/blob/cb1fdbb93cf406e17b07d14e8c5494e66d0e61d6/Stock.py#L69

제가 이 69라인을 주석 처리하고 보낸다는걸 깜박했습니다. 
참고 부탁드립니다.

**Comment by wansanp** [comment]
반영 했습니다. 고맙습니다.
